name: Benchmark

on:
  workflow_dispatch:

jobs:
  Benchmark:
    runs-on: ubuntu-latest
    steps:    
    - uses: actions/checkout@v2
    
    - name: Setup .NET and Checkout
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.x
        
    - name: Run Benchmark
      run: sudo dotnet run --configuration Release --project ./CrackingTheCodingInterview/ -- --artifacts ./BenchmarkDotNet.Artifacts/ --info --stopOnFirstError